version: '3.8'

services:
  sales-page:
    image: nginx:alpine
    container_name: sales-page-web
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge

volumes:
  html-data:
